---
title: "Capstone"
output: html_document
date: "2026-03-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(dplyr)
setwd("/Users/sophiekemprecos/Desktop/Capstone")
```

```{r}
cleaned<-read.csv("cleaned.csv") #read in cleaned data

# fix outcome variable 
cleaned <- cleaned %>%
  mutate(V1398 = ifelse(
    V1397 == 0 & is.na(V1398),
    0,
    V1398))

cleaned <- cleaned %>%
  filter(!is.na(V1398))

```

```{r}
#fixing race variable
cleaned <- cleaned %>%
  mutate(Race = case_when(
    rowSums(across(c(V1952, V1953, V1951, V1954,V1955,V1956,V1957)) == 1) > 1 ~ "Multiracial",
    V1952 == 1 ~ "White",
    V1953 == 1 ~ "Black",
    V1951 == 1 ~ "Hispanic",
    V1954 == 1 ~ "American Indian",
    V1955 == 1 ~ "Asian",
    V1956 == 1 ~ "Native Hawaiian",
    V1957 == 1 ~ "Other Race",
    TRUE ~ NA_character_
  ))

cleaned$Race <- factor(cleaned$Race)
```

```{r, ignore!}
#renaming variables/cleaning
cleaned <- cleaned %>%
  rename("Number Infractions" = V1398)

cleaned <- cleaned %>%
  rename("Marital Status" = V0022)

cleaned$`Marital Status` <- factor(cleaned$`Marital Status`)

cleaned <- cleaned %>%
  rename("Armed Forces" = V0023)

cleaned <- cleaned %>%
  rename("Times Arrested" = V0909)

cleaned <- cleaned %>%
  rename("Years of Education" = V0935)

cleaned <- cleaned %>%
  rename("ADD/ADHD" = V0942)

cleaned <- cleaned %>%
  rename("Homeless" = V0958)

cleaned <- cleaned %>%
  rename("Children" = V0982)

cleaned <- cleaned %>%
  rename("Bipolar" = V1185)%>%
  rename("Depression" = V1186)%>%
  rename("Schizophrenia" = V1187)%>%
  rename("PTSD" = V1188)%>%
  rename("Anxiety" = V1189)%>%
  rename("Personality Disorder" = V1190)%>%
  rename("Other Diagnosis" = V1191)%>%
  rename("Mental Health Treatment" = V1204)

cleaned <- cleaned %>%
  rename("Alcoholism" = V1265)%>%
  rename("Cocaine"= V1316)%>%
  rename("Crack"= V1317)%>%
  rename("Heroin"= V1318)%>%
  rename("PCP"= V1319)%>%
  rename("Ecstasy"= V1320)%>%
  rename("Meth"= V1322)%>%
  rename("Alcohol/Drug Treatment"= V1374)
```

```{r}
#armed forces
cleaned <- cleaned %>%
  mutate(`Armed Forces` = ifelse(`Armed Forces` == 2, 0, `Armed Forces`))

# ADD/ADHD fix
cleaned <- cleaned %>%
  mutate(`ADD/ADHD` = ifelse(`ADD/ADHD` == 2, 0, `ADD/ADHD`))

# homeless fix
cleaned <- cleaned %>%
  mutate(Homeless = ifelse(Homeless == 2, 0, Homeless))

#children fix
cleaned <- cleaned %>%
  mutate(Children = ifelse(Children == 2, 0, Children))

#mental health fix
cleaned <- cleaned %>%
  mutate(Bipolar = ifelse(Bipolar == 2, 0, Bipolar))%>%
  mutate(Depression = ifelse(Depression == 2, 0, Depression))%>%
  mutate(Schizophrenia = ifelse(Schizophrenia == 2, 0, Schizophrenia))%>%
  mutate(PTSD = ifelse(PTSD == 2, 0, PTSD))%>%
  mutate(Anxiety = ifelse(Anxiety == 2, 0, Anxiety))%>%
  mutate(`Personality Disorder` = ifelse(`Personality Disorder` == 2, 0, `Personality Disorder`))%>%
  mutate(`Other Diagnosis` = ifelse(`Other Diagnosis` == 2, 0, `Other Diagnosis`))%>%
  mutate(`Mental Health Treatment` = ifelse(`Mental Health Treatment` == 2, 0, `Mental Health Treatment`))

#Drugs and alcohol
cleaned <- cleaned %>%
  mutate(Alcoholism = ifelse(Alcoholism == 2, 0, Alcoholism))%>%
  mutate(Cocaine = ifelse(Cocaine == 2, 0, Cocaine))%>%
  mutate(Crack = ifelse(Crack == 2, 0, Crack))%>%
  mutate(Heroin = ifelse(Heroin == 2, 0, Heroin))%>%
  mutate(PCP = ifelse(PCP == 2, 0, PCP))%>%
  mutate(Ecstasy = ifelse(Ecstasy == 2, 0, Ecstasy))%>%
  mutate(Meth = ifelse(Meth == 2, 0, Meth))%>%
  mutate(`Alcohol/Drug Treatment` = ifelse(`Alcohol/Drug Treatment` == 2, 0, `Alcohol/Drug Treatment`))

#offense type
cleaned <- cleaned %>%
  mutate(`Offense Type` = case_when(
    V0062 == 1 ~ "Violent",
    V0062 == 2 ~ "Property",
    V0062 == 3 ~ "Drug",
    V0062 == 4 ~ "Public Order",
    TRUE ~ NA_character_))

cleaned$`Offense Type` <- factor(cleaned$`Offense Type`)

#get rid of negatives
cleaned <- cleaned %>%
  mutate(across(
    c(`Number Infractions`, `Armed Forces`, `Times Arrested`, `Years of Education`, `ADD/ADHD`, `Homeless`, `Children`, `Bipolar`, Depression, Schizophrenia, PTSD, Anxiety, `Personality Disorder`, `Other Diagnosis`, `Mental Health Treatment`, Alcoholism, Cocaine, Crack, Heroin, PCP, Ecstasy, Meth, `Alcohol/Drug Treatment`),
    ~ ifelse(. < 0, NA, .)
  ))


```

# EDA
```{r}

plot(cleaned$`Number Infractions`, 
     main = "Spread of Inmate Infractions", 
     ylab = "Number of Infractions", 
     xlab = "Inmate Index",
     pch = 19, 
     col = rgb(0,0,1,0.3))

library(ggplot2)

ggplot(cleaned, aes(x = `Alcohol/Drug Treatment`, y = `Number Infractions`)) +
  geom_jitter(alpha = 0.4, color = "blue") + 
  geom_smooth(method = "lm", col = "red") + 
  labs(title = "Treatment vs. Rule Violations",
       x = "Alcohol or Drug Treatment",
       y = "Number of Infractions")

cleaned <- cleaned %>%
  mutate(Race = case_when(
    Race %in% c("Native Hawaiian", "American Indian", "Other Race") ~ "Other",
    TRUE ~ as.character(Race))) %>%
  mutate(num_diagnoses = rowSums(across(
    c(Bipolar, Depression, Schizophrenia, PTSD, Anxiety, `Personality Disorder`)),
    na.rm = TRUE))

cleaned$Race <- factor(cleaned$Race)

# Rule Violation by number of diagnoses
ggplot(cleaned, aes(x = as.factor(num_diagnoses), y = `Number Infractions`, fill = as.factor(num_diagnoses))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) + 
  geom_jitter(alpha = 0.3, width = 0.2, color = "darkgrey") + 
  labs(title = "Rule Violations by Number of Diagnoses",
       x = "Number of Diagnoses",
       y = "Number of Infractions") +
  theme_minimal() +
  theme(legend.position = "none")

# Rule violation by Race
ggplot(cleaned, aes(x = as.factor(Race), y = `Number Infractions`, fill = as.factor(Race))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) + 
  geom_jitter(alpha = 0.3, width = 0.2, color = "darkgrey") + 
  labs(title = "Rule Violations by Race",
       x = "Race",
       y = "Number of Infractions") +
  theme_minimal() +
  theme(legend.position = "none")

# Rule violation by Mental Health Treatment
ggplot(cleaned, aes(x = as.factor(`Mental Health Treatment`), y = `Number Infractions`, fill = as.factor(`Mental Health Treatment`))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) + 
  geom_jitter(alpha = 0.3, width = 0.2, color = "darkgrey") + 
  labs(title = "Rule Violations by Race",
       x = "Race",
       y = "Number of Infractions") +
  theme_minimal() +
  theme(legend.position = "none")
```
# Removing 0 Infractions
```{r}
df2 <- cleaned

df2 <- df2 %>%
  filter(`Number Infractions` >=1) 

median(df2$`Number Infractions`)
```

```{r}
# Rule Violation by number of diagnoses
ggplot(df2, aes(x = as.factor(num_diagnoses), y = `Number Infractions`, fill = as.factor(num_diagnoses))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) + 
  geom_jitter(alpha = 0.3, width = 0.2, color = "darkgrey") + 
  labs(title = "Rule Violations by Number of Diagnoses",
       x = "Number of Diagnoses",
       y = "Number of Infractions") +
  theme_minimal() +
  theme(legend.position = "none")

# Rule violation by Race
ggplot(df2, aes(x = as.factor(Race), y = `Number Infractions`, fill = as.factor(Race))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) + 
  geom_jitter(alpha = 0.3, width = 0.2, color = "darkgrey") + 
  labs(title = "Rule Violations by Race",
       x = "Race",
       y = "Number of Infractions") +
  theme_minimal() +
  theme(legend.position = "none")

# Rule violation by Gender
ggplot(df2, aes(x = as.factor(`Mental Health Treatment`), y = `Number Infractions`, fill = as.factor(`Mental Health Treatment`))) +
  geom_boxplot(outlier.shape = NA, alpha = 0.7) + 
  geom_jitter(alpha = 0.3, width = 0.2, color = "darkgrey") + 
  labs(title = "Rule Violations by Race",
       x = "Race",
       y = "Number of Infractions") +
  theme_minimal() +
  theme(legend.position = "none")
```


```{r}
library(AER)
#let's try running the model
model1 <- glm(`Number Infractions` ~ Race + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ `Personality Disorder`+ `Other Diagnosis`+ `Mental Health Treatment`+ Alcoholism+ Cocaine+ Crack+ Heroin+ PCP+ Ecstasy+ Meth+ `Alcohol/Drug Treatment`,
    family = poisson(link = "log"),
    data = cleaned)

dispersiontest(model1)

model2 <- glm(`Number Infractions` ~ Race + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ `Personality Disorder`+ `Other Diagnosis`+ `Mental Health Treatment`+ Alcoholism+ Cocaine+ `Alcohol/Drug Treatment`,
    family = poisson(link = "log"),
    data = cleaned)
dispersiontest(model2)



model4 <- glm(`Number Infractions` ~ Race + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ `Personality Disorder`+ `Other Diagnosis`+ `Mental Health Treatment`+ Alcoholism+ Cocaine+ `Alcohol/Drug Treatment`,
    family = binom(link = "logit"),
    data = cleaned)
dispersiontest(model4)
```
# Outlier removal
```{r}
top_20_violators <- cleaned %>%
  slice_max(order_by = `Number Infractions`, n = 20)

print(unique(top_20_violators$`Number Infractions`))

cleaned <- cleaned %>%
  filter(!(`Number Infractions` %in% c(175, 250)))

new_max <- max(cleaned$`Number Infractions`, na.rm = TRUE)
cat("The new maximum number of infractions is:", new_max)
```

# First Stage
## Defining a threshold
```{r}
cleaned$is_high_risk <- ifelse(cleaned$`Number Infractions` > 0, 1, 0)
```

## Logistic
```{r}
model_stage1 <- glm(is_high_risk ~ Race + `Times Arrested` + `Years of Education` + 
                    `ADD/ADHD` + Bipolar + Depression + Schizophrenia + 
                    `Mental Health Treatment` + Alcoholism + `Alcohol/Drug Treatment`, 
                    family = binomial(link = "logit"), 
                    data = cleaned)

summary(model_stage1)

model_stage2 <- glm(is_high_risk ~ Race + num_diagnoses + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ Heroin + Cocaine + Meth + `Mental Health Treatment`+ `Mental Health Treatment`:num_diagnoses+Alcoholism+ `Alcohol/Drug Treatment`, 
                    family = binomial(link = "logit"), data = cleaned)

summary(model_stage2)
```

# Negative Binomial
```{r}
library(MASS)
library(topmodels) # or the 'countreg' package

model_nb <- glm.nb(`Number Infractions` ~ Race + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ `Personality Disorder`+ Heroin + Cocaine + Meth + `Mental Health Treatment`+ Alcoholism+ `Alcohol/Drug Treatment`, data = cleaned)
summary(model_nb)

model_nb2 <- glm.nb(`Number Infractions` ~ Race + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ `Personality Disorder`+ Cocaine + `Mental Health Treatment`+ Alcoholism+ `Alcohol/Drug Treatment`, data = cleaned)
summary(model_nb2)

model_nb3<- glm.nb(`Number Infractions` ~ Race + num_diagnoses + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ Heroin + Cocaine + Meth + `Mental Health Treatment`+ `Mental Health Treatment`:num_diagnoses+Alcoholism+ `Alcohol/Drug Treatment`, data = cleaned)
summary(model_nb3)

model_nb4<- glm.nb(`Number Infractions` ~ Race + num_diagnoses + `Armed Forces` + `Marital Status` +`Times Arrested`+ `Years of Education`+ `ADD/ADHD`+ `Homeless`+ `Children`+ `Bipolar`+ Depression+ Schizophrenia+ PTSD+ Anxiety+ Heroin + Cocaine + Meth + `Mental Health Treatment`+ `Mental Health Treatment`:num_diagnoses+Alcoholism+ `Alcohol/Drug Treatment`, data = cleaned)
summary(model_nb4)
```

